In [36]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [37]:
df = pd.read_csv("breast-cancer-wisconsin.data",sep=',')
df.drop('1000025', inplace=True, axis=1)
df.head(5)

5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  5   4    4    5  7  10  3    2    1    2
1  3   1    1    1  2   2  3    1    1    2
2  6   8    8    1  3   4  3    7    1    2
3  4   1    1    3  2   1  3    1    1    2
4  8  10   10    8  7  10  9    7    1    4

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   5       698 non-null    int64 
 1   1       698 non-null    int64 
 2   1.1     698 non-null    int64 
 3   1.2     698 non-null    int64 
 4   2       698 non-null    int64 
 5   1.3     698 non-null    object
 6   3       698 non-null    int64 
 7   1.4     698 non-null    int64 
 8   1.5     698 non-null    int64 
 9   2.1     698 non-null    int64 
dtypes: int64(9), object(1)
memory usage: 54.7+ KB


In [39]:
pd.isnull(df).head()

5      1    1.1    1.2      2    1.3      3    1.4    1.5    2.1
0  False  False  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False  False  False  False

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   5       698 non-null    int64 
 1   1       698 non-null    int64 
 2   1.1     698 non-null    int64 
 3   1.2     698 non-null    int64 
 4   2       698 non-null    int64 
 5   1.3     698 non-null    object
 6   3       698 non-null    int64 
 7   1.4     698 non-null    int64 
 8   1.5     698 non-null    int64 
 9   2.1     698 non-null    int64 
dtypes: int64(9), object(1)
memory usage: 54.7+ KB


In [24]:
def train_test_split(X, y, random_state=42, test_size=0.2):
    """
    Splits the data into training and testing sets.

    Parameters:
        X (numpy.ndarray): Features array of shape (n_samples, n_features).
        y (numpy.ndarray): Target array of shape (n_samples,).
        random_state (int): Seed for the random number generator. Default is 42.
        test_size (float): Proportion of samples to include in the test set. Default is 0.2.

    Returns:
        Tuple[numpy.ndarray]: A tuple containing X_train, X_test, y_train, y_test.
    """
    # Get number of samples
    n_samples = X.shape[0]

    # Set the seed for the random number generator
    np.random.seed(random_state)

    # Shuffle the indices
    shuffled_indices = np.random.permutation(np.arange(n_samples))

    # Determine the size of the test set
    test_size = int(n_samples * test_size)

    # Split the indices into test and train
    test_indices = shuffled_indices[:test_size]
    train_indices = shuffled_indices[test_size:]

    # Split the features and target arrays into test and train
    X_train, X_test = X[train_indices], X[test_indices]
    y_train, y_test = y[train_indices], y[test_indices]

    return X_train, X_test, y_train, y_test

In [25]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values.reshape(-1,1)
print(X)
print(y)

[[5 4 4 ... 3 2 1]
 [3 1 1 ... 3 1 1]
 [6 8 8 ... 3 7 1]
 ...
 [5 10 10 ... 8 10 2]
 [4 8 6 ... 10 6 1]
 [4 8 8 ... 10 4 1]]
[[2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]


In [26]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 42, test_size=0.2)
print(X_train)
print(y_train)

[[8 6 4 ... 3 1 1]
 [3 1 1 ... 7 1 1]
 [10 3 6 ... 4 10 2]
 ...
 [5 1 1 ... 3 1 1]
 [10 10 10 ... 2 8 1]
 [8 2 3 ... 7 1 1]]
[[4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]


In [27]:
class Node():
    def __init__(self, feature = None,threshold = None, left = None, right = None, gain = None, value = None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.gain = gain
        self.value = value

In [28]:
class Decision_tree():
    def __init__(self, min_samples=2, max_depth=2):
        self.min_samples = min_samples
        self.max_depth = max_depth
        
    def split_Node(self, dataset, feature, threshold):
        left_node = []
        right_node = []
        for row in dataset:
            if row[feature] == threshold:
                left_node.append(row)
            else:
                right_node.append(row)
        left_node = np.array(left_node)
        right_node = np.array(right_node)
        return left_node, right_node
    def compute_entropy(self, y):
        entropy = 0.
        labels = np.unique(y)
        for i in labels:
            pi = y[y == i]
            ep = len(pi)/len(y)
            if ep != 0:
                entropy += -ep*np.log2(ep)
        return entropy
    def compute_information_gain(self, parent, left, right):
        enl = self.compute_entropy(left)
        enr = self.compute_entropy(right)
        enpar = self.compute_entropy(parent)
        in_gain = enpar
        if enl != 0:
            in_gain = in_gain - (len(left) / len(parent)) * enl
        if enr != 0:
            in_gain = in_gain - (len(right) / len(parent)) * enr
        return in_gain
    def find_best_split(self, dataset, num_features, k):
        best_split = { 'gain': -1, 'feature': None, 'threshold': None}
        Features = np.random.permutation(num_features)
        for idFeature in range(k):
            feature = Features[idFeature]
            thresholds = np.unique(dataset[:, feature])
            for i in thresholds:
                left_dataset, right_dataset = self.split_Node( dataset, feature, i)
                if len(left_dataset) and len(right_dataset):
                    y, left_check, right_check = dataset[:,-1],left_dataset[:,-1], right_dataset[:,-1]
                    ig = self.compute_information_gain(y, left_check, right_check)
                    if ig >best_split['gain']:
                        best_split["gain"] = ig
                        best_split["feature"] = feature
                        best_split["threshold"]  = i
                        best_split["left_dataset"] = left_dataset
                        best_split["right_dataset"] = right_dataset
        return best_split
    def caculate_leaf_val(self, y):
        y = list(y)
        value = max(y, key=y.count)
        return value
    def build_tree(self, dataset,k, cur_depth = 0):
        X,y = dataset[:, :-1], dataset[:,-1]
        n_samples, n_features = X.shape
        if cur_depth <= self.max_depth and n_samples >= self.min_samples:
            best_split = self.find_best_split(dataset, n_features, k)
            if best_split["gain"]:
                left_node = self.build_tree(best_split["left_dataset"],k, cur_depth + 1)
                right_node = self.build_tree(best_split["right_dataset"],k, cur_depth + 1)
                return Node(best_split["feature"], best_split["threshold"], left_node, 
                            right_node, best_split["gain"]) 
        leaf_value = self.caculate_leaf_val(y)
        return Node(value = leaf_value)
    def fit(self, dataset, k):
        self.root = self.build_tree(dataset, k)
    def make_predict(self, X, node):
        if node.value != None:
            return node.value
       
        feature = node.feature
        if X[feature] == node.threshold:
            return self.make_predict(X, node.left)
        else:
            return self.make_predict(X, node.right)
    def predict(self, X):
        prediction = []
        for i in range(len(X)):
            x = X[i]
            yhat = self.make_predict(x, self.root)
            prediction.append(yhat)
        np.array(prediction)
        return prediction

In [48]:
class RandomForest():
    def __init__(self, min_samples=2,max_depth=10,n_trees=7):
        self.min_samples=min_samples
        self.max_depth=max_depth
        self.n_trees=n_trees
        self.trees = []
    def fit(self,X,y):
        self.trees = []
        dataset = np.concatenate((X,y),axis=1)
        n_features = X.shape[1]
        for NumTree in range(self.n_trees):
            Tree = Decision_tree(min_samples = self.min_samples, max_depth=self.max_depth)
            Dataset_samp = self.boostrap(dataset)
            Tree.fit(Dataset_samp,9)
            self.trees.append(Tree)
        return self
    def boostrap(self, dataset):
        num_samples = dataset.shape[0]
        np.random.seed(1)
        indices = np.random.choice(num_samples, num_samples, replace=True)
        dataset_sample = dataset[indices]
        return dataset_sample
    def most_common(self, y):
        y = list(y)
        val_predict = max(y,key=y.count)
        return val_predict
    def Predict(self, X):
        predictions = np.array([tree.predict(X) for tree in self.trees])
        preds = np.swapaxes(predictions,0, 1)
        final_predictions = np.array([self.most_common(y) for y in preds])
        return final_predictions

In [49]:
def accuracy(y_true, y_pred):
    y_true = y_true.flatten()
    total_samples = len(y_true)
    correct_predictions = np.sum(y_true == y_pred)
    return (correct_predictions / total_samples)

In [53]:
model = RandomForest(2,10,10)
model.fit(X_train, y_train)
predictions = model.Predict(X_test)
accuracy(y_test, predictions)

KeyError: 'left_dataset'

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [52]:
dt =  Decision_tree(2,10)
dataset = np.concatenate((X_train,y_train),axis=1)
dt.fit(dataset,9)
predictions = dt.predict(X_test) #evaluate the model on the test data

# predictions = model.predict(X_test) #evaluate the model on the test data
accuracy(y_test, predictions)

0.935251798561151